experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: dataset_name
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.DGCF:
      meta:
        hyper_opt_alg: tpe
        hyper_max_evals: 20
        verbose: True
        save_weights: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: [loguniform, -9.21034037198, -6.90775527898]
      epochs: 3000
      factors: 64
      batch_size: 256
      l_w_bpr: [loguniform, 1.60943791243, 1.94591014906]
      l_w_ind: [loguniform, 1.60943791243, 1.94591014906]
      n_layers: [choice, [1, 2, 3, 4]]
      routing_iterations: 2
      intents: [choice, [2, 4, 8, 16]]
      seed: 42
      early_stopping:
        patience: 40
        mode: auto
        monitor: Recall@20
        verbose: True