experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: dataset_name
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.LightGCN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: True
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: 0.001
      epochs: 1000
      factors: 64
      batch_size: 64
      l_w: 1e-4
      n_layers: [ 1, 2, 3, 4 ]
      normalize: [ True, False ]
      seed: 123
      early_stopping:
        patience: 50
        mode: auto
        monitor: Recall@20
        verbose: True