experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    test_path: ../data/{0}/train.tsv
  dataset:
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [nDCG, Recall, Precision, HR, MAR, MAP, MRR, F1]
    rel_threshold: 0
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.LightGCN:
      meta:
        verbose: True
        save_weights: True
        validation_rate: 19
        validation_metric: Recall@20
        restore: False
      lr: 0.001
      epochs: 19
      factors: 64
      batch_size: 32
      l_w: 1e-4
      n_layers: 4
      normalize: False
      seed: 123
    # 8