experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    test_path: ../data/{0}/test.tsv
  dataset: dataset_name
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
#    external.NGCF:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        validation_rate: 10
#        validation_metric: Recall@20
#        restore: False
#        write_best_iterations: True
#      lr: 0.0005
#      epochs: 200
#      factors: 64
#      batch_size: 1024
#      l_w: 1e-5
#      n_layers: 3
#      weight_size: 64
#      node_dropout: 0.1
#      message_dropout: 0.1
#      normalize: True
#      seed: 42
#      early_stopping:
#        patience: 5
#        mode: auto
#        monitor: Recall@20
#        verbose: True
#    external.LightGCN:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        validation_rate: 20
#        validation_metric: Recall@20
#        restore: False
#        write_best_iterations: True
#      lr: 0.001
#      epochs: 1000
#      factors: 64
#      batch_size: 2048
#      l_w: 1e-4
#      n_layers: 3
#      normalize: True
#      seed: 42
#      early_stopping:
#        patience: 5
#        mode: auto
#        monitor: Recall@20
#        verbose: True
#    # 8
#    external.DGCF:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        validation_rate: 1
#        validation_metric: Recall@20
#        restore: False
#        write_best_iterations: True
#      lr: 0.001
#      epochs: 3000
#      factors: 64
#      batch_size: 1024
#      l_w_bpr: 1e-3
#      l_w_ind: 0.01
#      n_layers: 1
#      routing_iterations: 2
#      intents: 4
#      seed: 42
#      early_stopping:
#        patience: 40
#        mode: auto
#        monitor: Recall@20
#        verbose: True
#    # 64
    external.LRGCCF:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: 0.001
      epochs: 350
      factors: 64
      batch_size: 2048
      l_w: 0.01
      n_layers: 3
      normalize: True
      num_neg: 5
      seed: 42
    # 8
#    external.SGL:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        validation_rate: 1
#        validation_metric: Recall@20
#        restore: False
#        write_best_iterations: True
#      lr: 0.001
#      epochs: 1000
#      batch_size: 1024
#      factors: 64
#      l_w: 1e-4
#      n_layers: 3
#      ssl_temp: 0.2
#      ssl_reg: 0.5
#      ssl_ratio: 0.1
#      sampling: ed
#      seed: 2021
#      early_stopping:
#        patience: 10
#        mode: auto
#        monitor: Recall@20
#        verbose: True
    # 96
#    external.UltraGCN:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        validation_rate: 5
#        validation_metric: Recall@20
#        restore: False
#        write_best_iterations: True
#      lr: 1e-3
#      epochs: 2000
#      factors: 64
#      batch_size: 1024
#      g: 1e-4
#      l: 2.75
#      w1: 1e-8
#      w2: 1.0
#      w3: 1.0
#      w4: 1e-8
#      ii_n_n: 10
#      n_n: 500
#      n_w: 500
#      s_s_p: False
#      i_w: 1e-4
#      seed: 42
#      early_stopping:
#        patience: 15
#        mode: auto
#        monitor: Recall@20
#        verbose: True
#    # 40
#    external.SVDGCN:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        validation_rate: 1
#        validation_metric: Recall@20
#        restore: False
#        write_best_iterations: True
#      factors: 64
#      epochs: 15
#      batch_size: 1024
#      l_w: 0.01
#      lr: 7.0
#      req_vec: [60, 90]
#      beta: 2.0
#      alpha: [2.0, 3.0]
#      coef_u: [0.1, 0.3, 0.5, 0.7]
#      coef_i: [0.1, 0.3, 0.5, 0.7]
#      seed: 123
    # 64
    # no early stopping because epochs are very low