experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: dataset_name
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.NGCF:
      meta:
        hyper_opt_alg: tpe
        hyper_max_evals: 20
        verbose: True
        save_weights: False
        validation_rate: 3
        validation_metric: Recall@20
        save_recs: True
        restore: False
        write_best_iterations: True
      lr: 0.0010492631473907471
      epochs: 3
      factors: 64
      batch_size: 128
      l_w: 0.08623551848300251
      n_layers: 1
      weight_size: 64
      node_dropout: 0.5704755544541924
      message_dropout: 0.37665593943318876
      normalize: True
      seed: 42