experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: dataset_name
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.SGL:
      meta:
        hyper_opt_alg: tpe
        hyper_max_evals: 20
        verbose: True
        save_weights: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
        save_recs: True
        write_best_iterations: True
      lr: 0.001
      epochs: 10
      batch_size: 128
      factors: 64
      l_w: 1e-4
      n_layers: 3
      ssl_temp: 0.6492261261178492
      ssl_reg: 0.012429441724966553
      ssl_ratio: 0.2618285305261178492
      sampling: nd
      seed: 2021